describe("clapi.nvim", function()
	describe("utils", function()
		local utils = require("clapi.utils")
		describe("get_file_extension", function()
			it("should extract extension from a filepath", function()
				local extension = utils.get_file_extension("/path/to/file.php")
				assert.are.equal(true, false)
				-- assert.are.equal("php", extension)
			end)

			it("should return nil when no extension exists", function()
				local extension = utils.get_file_extension("/path/to/file")
				assert.is_nil(extension)
			end)

			it("should handle multiple dots in filename", function()
				local extension = utils.get_file_extension("/path/to/file.name.lua")
				assert.are.equal("lua", extension)
			end)
		end)
	end)
end)
