name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    # runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Install Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: stable
      - name: Install dependencies
        run: |
          git clone --depth 1 https://github.com/nvim-lua/plenary.nvim ~/.local/share/nvim/site/pack/vendor/start/plenary.nvim
          git clone --depth 1 https://github.com/nvim-telescope/telescope.nvim.git ~/.local/share/nvim/site/pack/vendor/start/telescope.nvim
          git clone --depth 1 https://github.com/nvim-treesitter/nvim-treesitter ~/.local/share/nvim/site/pack/vendor/start/nvim-treesitter.nvim
          git clone --depth 1 https://github.com/neovim/nvim-lspconfig.git ~/.local/share/nvim/site/pack/vendor/start/nvim-lspconfig.git
          git clone --depth 1 https://github.com/williamboman/mason.nvim.git ~/.local/share/nvim/site/pack/vendor/start/mason.nvim.git
          git clone --depth 1 https://github.com/williamboman/mason-lspconfig.nvim.git ~/.local/share/nvim/site/pack/vendor/start/mason-lspconfig.nvim.git
          git clone --depth 1 https://github.com/WhoIsSethDaniel/mason-tool-installer.nvim.git ~/.local/share/nvim/site/pack/vendor/start/mason-tool-installer.nvim.git
          git clone --depth 1 https://github.com/hrsh7th/nvim-cmp.git ~/.local/share/nvim/site/pack/vendor/start/nvim-cmp.git
          git clone --depth 1 https://github.com/hrsh7th/cmp-nvim-lsp.git ~/.local/share/nvim/site/pack/vendor/start/cmp-nvim-lsp.git
          git submodule update --init
          sudo apt update -y
          sudo apt install build-essential php php-xml php-mbstring php-curl composer -y
      - name: Debugging environment
        if: always()
        run: |
          ls ~/.local/share/nvim
          find ~/.local/share/nvim -type d | grep mason
      - name: Prepare Mason
        run: |
          mkdir -p ~/.local/share/nvim/mason
          mkdir -p ~/.local/share/nvim/mason/bin
          mkdir -p ~/.local/share/nvim/mason/packages
          
          # Pre-install phpactor manually if possible
          if [ ! -d ~/.local/share/nvim/mason/packages/phpactor ]; then
            mkdir -p ~/.local/share/nvim/mason/packages/phpactor
            git clone --depth 1 https://github.com/phpactor/phpactor ~/.local/share/nvim/mason/packages/phpactor
            cd ~/.local/share/nvim/mason/packages/phpactor
            composer install --no-dev -o
            ln -sf ~/.local/share/nvim/mason/packages/phpactor/bin/phpactor ~/.local/share/nvim/mason/bin/phpactor
          fi
      - name: Run Tests
        run: make test
      - name: Debugging environment
        if: always()
        run: |
          ls ~/.local/share/nvim
          find ~/.local/share/nvim -type d | grep mason
