name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: stable

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          # cache: 'maven'  # Change to 'gradle' if using Gradle
      
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: xml
          coverage: none  # Options: none, xdebug, pcov
          tools: composer:v2

      - name: Install dependencies
        run: |
          git clone --depth 1 https://github.com/nvim-lua/plenary.nvim ~/.local/share/nvim/site/pack/vendor/start/plenary.nvim
          git clone --depth 1 https://github.com/nvim-telescope/telescope.nvim.git ~/.local/share/nvim/site/pack/vendor/start/telescope.nvim
          git clone --depth 1 https://github.com/nvim-treesitter/nvim-treesitter ~/.local/share/nvim/site/pack/vendor/start/nvim-treesitter.nvim
          git clone --depth 1 https://github.com/neovim/nvim-lspconfig.git ~/.local/share/nvim/site/pack/vendor/start/nvim-lspconfig.git
          git clone --depth 1 https://github.com/williamboman/mason.nvim.git ~/.local/share/nvim/site/pack/vendor/start/mason.nvim.git
          git clone --depth 1 https://github.com/williamboman/mason-lspconfig.nvim.git ~/.local/share/nvim/site/pack/vendor/start/mason-lspconfig.nvim.git
          git clone --depth 1 https://github.com/WhoIsSethDaniel/mason-tool-installer.nvim.git ~/.local/share/nvim/site/pack/vendor/start/mason-tool-installer.nvim.git
          git clone --depth 1 https://github.com/hrsh7th/nvim-cmp.git ~/.local/share/nvim/site/pack/vendor/start/nvim-cmp.git
          git clone --depth 1 https://github.com/hrsh7th/cmp-nvim-lsp.git ~/.local/share/nvim/site/pack/vendor/start/cmp-nvim-lsp.git
          sudo apt update -y
          sudo apt install build-essential php php-xml composer openjdk-21-jdk -y --reinstall
      - name: Run Unit Tests
        run: make test-unit
      - name: Run Functional Tests
        run: make test-functional
      - name: debug
        if: always()
        run: |
          # sudo cat ~/.local/state/nvim/lsp.log
          java --version
